# Generated by Django 4.1.3 on 2023-02-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=256)),
                ('birthday', models.DateField()),
                ('discount', models.FloatField()),
                ('home_address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('contact', models.CharField(max_length=256)),
                ('place_id', models.CharField(max_length=128)),
                ('school_name', models.CharField(max_length=256)),
                ('school_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('recom_text', models.TextField()),
                ('link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Reqviziti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('couunt', models.IntegerField()),
                ('couunt_komp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reqviziti_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('reqs_2_id', models.CharField(max_length=64)),
                ('present', models.BooleanField()),
                ('start_count', models.IntegerField()),
                ('reqvizit_count_present', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('school_id', models.CharField(max_length=64)),
                ('okpo', models.CharField(max_length=64)),
                ('headmaster', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sotrud_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Spisok_Reqviziti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('reqs_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('name_min', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('subs', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_main', models.CharField(max_length=128)),
                ('id_cat_main', models.CharField(max_length=128)),
                ('sub_cat', models.CharField(max_length=128)),
                ('id_sub_cat', models.CharField(max_length=128)),
                ('sub_sub_cat', models.CharField(max_length=128)),
                ('id_sub_sub_cat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WeekTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_day', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='What_have_we_learned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zp_Prepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp_ochno', models.IntegerField()),
                ('zp_ochno_min', models.IntegerField()),
                ('zp_online_sad', models.IntegerField()),
                ('zp_online_school', models.IntegerField()),
                ('zp_podrabotka_hour', models.IntegerField()),
                ('zp_online_min', models.IntegerField()),
                ('zp_ind_min', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Zadania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('subsubject', models.CharField(max_length=128)),
                ('typ', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('main_file', models.CharField(max_length=512)),
                ('pdf_file', models.CharField(max_length=512)),
                ('reqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.reqviziti')),
            ],
        ),
        migrations.CreateModel(
            name='Dohodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summ', models.IntegerField()),
                ('full_name', models.CharField(max_length=128)),
                ('classes_count', models.IntegerField()),
                ('month', models.CharField(max_length=128)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.clients')),
            ],
        ),
    ]
