# Generated by Django 4.1.3 on 2023-02-11 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0002_schools_delete_shools_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dohodi',
            options={'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='child_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='ФИО ребенка'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='home_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='zadania',
            name='reqs',
            field=models.ManyToManyField(to='file1.reqviziti', verbose_name='Реквизиты'),
        ),
    ]
