# Generated by Django 4.1.3 on 2023-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0003_alter_dohodi_options_alter_clients_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektable',
            name='status',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Статус'),
        ),
    ]
