# Generated by Django 4.1.3 on 2023-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0004_alter_weektable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadania',
            name='reqs_text',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Реквизиты текст'),
        ),
        migrations.AlterField(
            model_name='zadania',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='zadania',
            name='main_file',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Главный файл'),
        ),
        migrations.AlterField(
            model_name='zadania',
            name='pdf_file',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='zadania',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Название задания'),
        ),
    ]
