# Generated by Django 4.1.3 on 2023-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0005_zadania_reqs_text_alter_zadania_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadania',
            name='task_id',
            field=models.CharField(max_length=128, verbose_name='ID задания'),
        ),
    ]
