# Generated by Django 4.1.3 on 2023-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0006_alter_zadania_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='headmaster',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='okpo',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ОКПО'),
        ),
    ]
