# Generated by Django 4.1.3 on 2023-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0007_alter_schools_headmaster_alter_schools_okpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dohodi',
            name='classes_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество занятий'),
        ),
    ]
