# Generated by Django 4.1.3 on 2023-02-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0009_alter_places_address_alter_places_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subs',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Подписи'),
        ),
    ]
