# Generated by Django 4.1.3 on 2023-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0010_alter_teachers_email_alter_teachers_subs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spisok_reqviziti',
            options={'verbose_name': 'Список Реквзит', 'verbose_name_plural': 'Список реквизитов'},
        ),
        migrations.AlterField(
            model_name='reqviziti_2',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активный?'),
        ),
        migrations.AlterField(
            model_name='reqviziti_2',
            name='reqvizit_count_present',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во реквизита для подарка'),
        ),
        migrations.AlterField(
            model_name='reqviziti_2',
            name='start_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость в звездах'),
        ),
    ]
