# Generated by Django 4.1.3 on 2023-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0011_alter_spisok_reqviziti_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqviziti_2',
            name='present',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Является подарком?'),
        ),
    ]
