# Generated by Django 4.1.3 on 2023-02-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0012_alter_reqviziti_2_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iexact_year', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('1kl', '1 класс'), ('2kl', '2 класс'), ('3kl', '3 класс'), ('4kl', '4 класс')], max_length=64, verbose_name='Пр.Возраст')),
                ('week_number', models.CharField(max_length=64, verbose_name='№ неделм план')),
                ('idformat', models.CharField(choices=[('ochno', 'Очно'), ('online', 'Онлайн')], max_length=64, verbose_name='Формат факт')),
                ('task_str_id', models.CharField(blank=True, default=False, max_length=64, null=True, verbose_name='ID задания')),
                ('dz_str_id', models.CharField(blank=True, default=False, max_length=64, null=True, verbose_name='ID дз')),
                ('dz', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dz', to='file1.zadania')),
                ('recom', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recom', to='file1.recomendation')),
                ('task', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='file1.zadania')),
            ],
        ),
    ]
