# Generated by Django 4.1.3 on 2023-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0014_alter_year_program_dz_alter_year_program_idformat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_program',
            name='idformat',
            field=models.CharField(choices=[('очно', 'oчно'), ('онлайн', 'oнлайн')], max_length=64, verbose_name='Формат факт'),
        ),
        migrations.AlterField(
            model_name='year_program',
            name='iexact_year',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('1 класс', '1 класс'), ('2 класс', '2 класс'), ('3 класс', '3 класс'), ('4 класс', '4 класс')], max_length=64, verbose_name='Пр.Возраст'),
        ),
    ]
