# Generated by Django 4.1.3 on 2023-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0015_alter_year_program_idformat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year_program',
            options={'verbose_name': 'Программа на год', 'verbose_name_plural': 'Программа на год'},
        ),
        migrations.AddField(
            model_name='year_program',
            name='raska_online',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Рас-ка онлайн'),
        ),
        migrations.AlterField(
            model_name='year_program',
            name='dz_str_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ID дз'),
        ),
        migrations.AlterField(
            model_name='year_program',
            name='task_str_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ID задания'),
        ),
    ]
