# Generated by Django 4.1.3 on 2023-02-25 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0016_alter_year_program_options_year_program_raska_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_program',
            name='iexact_year',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('1 класс', '1 класс'), ('2 класс', '2 класс'), ('3 класс', '3 класс'), ('4 класс', '4 класс'), ('5 класс', '5 класс')], max_length=64, verbose_name='Пр.Возраст'),
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=128, verbose_name='ф')),
                ('week_day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=128, verbose_name='День недели')),
                ('time', models.CharField(max_length=64, verbose_name='Время')),
                ('format_plan', models.CharField(choices=[('очно', 'oчно'), ('онлайн', 'oнлайн')], max_length=32, verbose_name='Формат план')),
                ('program_year', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('1 класс', '1 класс'), ('2 класс', '2 класс'), ('3 класс', '3 класс'), ('4 класс', '4 класс'), ('5 класс', '5 класс')], max_length=64, verbose_name='Программный возраст')),
                ('kabinet', models.CharField(max_length=128, verbose_name='Кабинет для занятий')),
                ('gruop_type', models.CharField(choices=[('школа', 'школа'), ('сад', 'сад'), ('инд', 'инд')], max_length=256, verbose_name='Тип группы')),
                ('zoom_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка зум')),
                ('id_zoom', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='ID zoom')),
                ('pass_zoom', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Zoom pass')),
                ('journal', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Журнал')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала занятий')),
                ('start_program', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='Начало программы')),
                ('fict_group', models.BooleanField(verbose_name='Фиктивные группы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания программы')),
                ('otchisl', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Отчисление от школы %')),
                ('where_pay', models.CharField(choices=[('школа', 'школа'), ('декарт', 'декарт')], max_length=128, verbose_name='Куда оплата')),
                ('tax', models.IntegerField(default=17, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Налог')),
                ('payment_per_class', models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Стоимость за занятие')),
                ('payment_per_month', models.IntegerField(default=5000, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Стоимость за занятие')),
                ('extra_payment', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Дополнительные выплаты (Самозянатые)')),
                ('mos_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на mos')),
                ('dop_otchisl_dekart', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Доп отчисление от школы В декарт')),
                ('pedagog_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagog_fact', to='file1.teachers', verbose_name='Педагоги')),
                ('pedagog_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagog_table', to='file1.teachers', verbose_name='Педагоги')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.places', verbose_name='Место')),
            ],
        ),
    ]
