# Generated by Django 4.1.3 on 2023-02-25 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0017_alter_year_program_iexact_year_raspisanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspisanie',
            name='payment_per_month',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Стоимость за месяц'),
        ),
    ]
