# Generated by Django 4.1.3 on 2023-03-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0019_alter_raspisanie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otrabotka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=512, verbose_name='ФИО ребенка')),
                ('progul', models.DateField(blank=True, null=True, verbose_name='Прогул')),
                ('otrabotka', models.DateField(blank=True, null=True, verbose_name='Прогул')),
                ('group_name_progul', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Название группы (Прогул)')),
                ('group_name_otrabotka', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Название группы (Прогул)')),
                ('status', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Статус')),
                ('message_for_pedagog_otr', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Сообщ для педагога в группе отработка')),
                ('message_date', models.DateField(blank=True, null=True, verbose_name='Дата сообщения в обычную группу')),
                ('message_for_pedagog_obich', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Сообщ для педагога в обычной группе')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file1.raspisanie', verbose_name='Id группы')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file1.groups', verbose_name='ID ученика')),
            ],
        ),
    ]
