# Generated by Django 4.1.3 on 2023-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0020_otrabotka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrabotka',
            options={'verbose_name': 'Отработка', 'verbose_name_plural': 'Отработка'},
        ),
        migrations.AddField(
            model_name='otrabotka',
            name='message_group_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название группы (сообщение)'),
        ),
        migrations.AlterField(
            model_name='otrabotka',
            name='otrabotka',
            field=models.DateField(blank=True, null=True, verbose_name='Отработка'),
        ),
    ]
