# Generated by Django 4.1.3 on 2023-03-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0022_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='gifts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.reqviziti_2'),
        ),
    ]
