# Generated by Django 4.1.3 on 2023-03-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0023_alter_gifts_gifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('child_name', models.CharField(max_length=256)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.reqviziti_2')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.groups')),
            ],
        ),
    ]
